# Font
font_family      JetBrainsMono Nerd Font
font_size        13.0

# Transparency
background_opacity 0.88
dynamic_background_color no

# Colors — dark purple theme
background            #12111a
foreground            #cdd6f4

selection_background  #7f77dd
selection_foreground  #12111a

# Cursor
cursor                #7f77dd
cursor_text_color     #12111a

# Normal colors
color0  #1e1d2e
color1  #f28b82
color2  #1d9e75
color3  #e8b84b
color4  #7f77dd
color5  #b07dd6
color6  #56c4c4
color7  #cdd6f4

# Bright colors
color8  #444461
color9  #ff9090
color10 #25c990
color11 #f5cc6e
color12 #a09ae8
color13 #c89de8
color14 #79d8d8
color15 #ffffff

# Window
window_padding_width    12
hide_window_decorations yes
remember_window_size    yes

# Scrollback
scrollback_lines 5000

# Misc
enable_audio_bell no
confirm_on_os_window_close 0
